import "../style/globals.css";
import type { Metadata } from "next";
import { poppins, rubik } from "@/lib/font";
import { cn } from "@/lib/class-merge";
import Navbar from "@/components/common/navbar";

export const metadata: Metadata = {
  title: "Arief Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${rubik.variable} antialiased`} suppressHydrationWarning>
        <main
          className={cn(
            "flex relative screen break-words min-h-screen items-center justify-between pt-14 pb-4 px-40 max-md:p-4 bg-transparent max-sm:pt-20 bg-[radial-gradient(#000000_0.1px,transparent_1px)] [background-size:16px_16px]",
            { "bg-white": "#E6E7EB" }
          )}
        >
          {/* NAVBAR ->  */}
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
